// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productFieldNames          = builder.RawFieldNames(&Product{})
	productRows                = strings.Join(productFieldNames, ",")
	productRowsExpectAutoSet   = strings.Join(stringx.Remove(productFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	productRowsWithPlaceHolder = strings.Join(stringx.Remove(productFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"
)

type (
	productModel interface {
		Insert(ctx context.Context, data *Product) (sql.Result, error)
		FindAll(ctx context.Context, orderBy string) ([]Product, error)
		FindPaginations(ctx context.Context, where string, page, pageSize int64) ([]Product, error)
		FindIdsAll(ctx context.Context, ids string) ([]Product, error)
		FindOne(ctx context.Context, id uint64) (*Product, error)
		Update(ctx context.Context, data *Product) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultProductModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Product struct {
		Id          uint64    `db:"id"`          // 商品id
		CateId      uint64    `db:"cateId"`      // 类别Id
		Title       string    `db:"title"`       // 商品名称
		Property    string    `db:"property"`    // 商品属性
		CoverPic    string    `db:"coverPic"`    // 商品封面
		Images      string    `db:"images"`      // 图片地址,逗号分隔
		Detail      string    `db:"detail"`      // 商品详情
		MtPrice     float64   `db:"mtPrice"`     // 市场价格,单位-元保留两位小数
		DisPrice    float64   `db:"disPrice"`    // 折扣价格, 单位元-保留两位小数
		Stock       uint64    `db:"stock"`       // 库存数量
		State       uint64    `db:"state"`       // 商品状态.1-在售 2-下架 3-删除
		CreateTime  time.Time `db:"create_time"` // 创建时间
		UpdateTime  time.Time `db:"update_time"` // 更新时间
		SalesVolume int64     `db:"salesVolume"` // 销量
	}
)

func newProductModel(conn sqlx.SqlConn) *defaultProductModel {
	return &defaultProductModel{
		conn:  conn,
		table: "`product`",
	}
}

func (m *defaultProductModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProductModel) FindAll(ctx context.Context, where string) ([]Product, error) {
	var resp []Product
	var err error
	if len(where) == 0 {
		query := fmt.Sprintf("select %s from %s order by create_time desc", productRows, m.table)
		err = m.conn.QueryRowsCtx(ctx, &resp, query)
	} else {
		query := fmt.Sprintf("select %s from %s where %s order by create_time desc", productRows, m.table)
		err = m.conn.QueryRowsCtx(ctx, &resp, query, where)
	}
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// pagination
func (m *defaultProductModel) FindPaginations(ctx context.Context, where string, page, pageSize int64) ([]Product, error) {
	var resp []Product
	var err error
	offset := (page - 1) * pageSize
	if len(where) == 0 {
		query := fmt.Sprintf("select %s from %s order by create_time desc limit ?,?", productRows, m.table)
		err = m.conn.QueryRowsCtx(ctx, &resp, query, offset, pageSize)
	} else {
		query := fmt.Sprintf("select %s from %s where ? order by create_time desc limit ?,?", productRows, m.table)
		err = m.conn.QueryRowsCtx(ctx, &resp, query, where, offset, pageSize)
	}
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductModel) FindIdsAll(ctx context.Context, ids string) ([]Product, error) {
	query := fmt.Sprintf("select %s from %s where id in (%s)", productRows, m.table, ids)
	var resp []Product
	err := m.conn.QueryRowsCtx(ctx, &resp, query)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductModel) FindOne(ctx context.Context, id uint64) (*Product, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productRows, m.table)
	var resp Product
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductModel) Insert(ctx context.Context, data *Product) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, productRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CateId, data.Title, data.Property, data.CoverPic, data.Images, data.Detail, data.MtPrice, data.DisPrice, data.Stock, data.State, data.SalesVolume)
	return ret, err
}

func (m *defaultProductModel) Update(ctx context.Context, data *Product) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.CateId, data.Title, data.Property, data.CoverPic, data.Images, data.Detail, data.MtPrice, data.DisPrice, data.Stock, data.State, data.SalesVolume, data.Id)
	return err
}

func (m *defaultProductModel) tableName() string {
	return m.table
}
