// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"microShop/product/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/recommend",
				Handler: RecommendHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/list",
				Handler: ProductListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/detail",
				Handler: ProductDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cate-list",
				Handler: cateListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/product"),
	)
}
