// Code generated by goctl. DO NOT EDIT.
package types

type BannerReq struct {
}

type BannerResply struct {
	Code    int64         `json:"code"`
	Message string        `json:"message"`
	Data    []*BannerItem `json:"data"`
}

type BannerItem struct {
	ID     int64  `json:"id"`
	Href   string `json:"href"`
	Title  string `json:"title"`
	Target string `json:"target"`
	Pic    string `json:"pic"`
}

type RecommendReq struct {
}

type RankingListReq struct {
}

type CommonResply struct {
	Code    int64                     `json:"Code"`
	Message string                    `json:"Message"`
	Data    map[int]map[string]string `json:"Data"`
}
