// Code generated by goctl. DO NOT EDIT!
// Source: home.proto

package server

import (
	"context"

	"microShop/home/rpc/internal/logic"
	"microShop/home/rpc/internal/svc"
	"microShop/home/rpc/types/home"
)

type HomeServer struct {
	svcCtx *svc.ServiceContext
	home.UnimplementedHomeServer
}

func NewHomeServer(svcCtx *svc.ServiceContext) *HomeServer {
	return &HomeServer{
		svcCtx: svcCtx,
	}
}

func (s *HomeServer) Banner(ctx context.Context, in *home.BannerReq) (*home.CommonResply, error) {
	l := logic.NewBannerLogic(ctx, s.svcCtx)
	return l.Banner(in)
}

func (s *HomeServer) Recommend(ctx context.Context, in *home.RecommendReq) (*home.CommonResply, error) {
	l := logic.NewRecommendLogic(ctx, s.svcCtx)
	return l.Recommend(in)
}

func (s *HomeServer) RankingList(ctx context.Context, in *home.RankingListReq) (*home.CommonResply, error) {
	l := logic.NewRankingListLogic(ctx, s.svcCtx)
	return l.RankingList(in)
}
