// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"microShop/home/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/banner",
				Handler: BannerHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/recommend",
				Handler: RecommendHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ranking-list",
				Handler: RankingListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/home"),
	)
}
