// Code generated by goctl. DO NOT EDIT.
package types

type ProductListReq struct {
	Page        int64  `json:"page"`
	PageSize    int64  `json:"pageSize"`
	ProductName string `json:"productName"`
}

type ProductListResply struct {
	Code       int64                     `json:"Code"`
	Message    string                    `json:"Message"`
	Page       int64                     `json:"Page"`
	PageSize   int64                     `json:"PageSize"`
	TotalCount int64                     `json:"TotalCount"`
	Data       map[int]map[string]string `json:"Data"`
}

type ProductDetailReq struct {
	PorductId int64 `json:"porductId"`
}

type CateListReq struct {
	Pid int64 `json:"Pid"`
}

type CategoryResply struct {
	Code    int64           `json:"Code"`
	Message string          `json:"Message"`
	Data    []*CategoryItem `json:"Data"`
}

type CategoryItem struct {
	ID       int64  `json:"Id"`
	ParentId int64  `json:"ParentId"`
	Name     string `json:"Name"`
	Status   int64  `json:"Status"`
}

type CommonResply struct {
	Code    int64                     `json:"Code"`
	Message string                    `json:"Message"`
	Data    map[int]map[string]string `json:"Data"`
}
