// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"microShop/orders/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: OrderListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: OrderDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/logistics",
				Handler: OrderLogisticsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/orders"),
	)
}
