// Code generated by goctl. DO NOT EDIT.
package types

type OrdersListReq struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"pageSize"`
}

type OrdersListResply struct {
	Code       int64                     `json:"Code"`
	Message    string                    `json:"Message"`
	Page       int64                     `json:"Page"`
	PageSize   int64                     `json:"PageSize"`
	TotalCount int64                     `json:"TotalCount"`
	Data       map[int]map[string]string `json:"Data"`
}

type OrderReq struct {
	OrderId int64 `json:"orderId"`
}

type CommonResply struct {
	Code    int64                     `json:"Code"`
	Message string                    `json:"Message"`
	Data    map[int]map[string]string `json:"Data"`
}
